# 5.MappingStress.py

import FunctionLibrary as fl
import time
import logging

def map_stress():
    # --- Timestamp ---
    start_time = time.time()
    batch_time_suffix = time.strftime('%Y.%m.%d-%H.%M.%S', time.localtime(start_time))

    # --- User-Defined Inputs ---
    # Path to the strain data generated by Script 3
    json_path = "OutputData/OutputFiles_Data_VB-APS-SSAO-6_25C_2025.10.13-12.28.56/strain_tensor_summary.json"
    sample_name = "VB-APS-SSAO-6_25C"
    
    # --- Material Properties ---
    # Young's Modulus (E) in GPa
    youngs_modulus = 303.0  # Alumina
    # Poisson's Ratio (ν)
    poissons_ratio = 0.21    # Alumina

    # --- Geometric and Measurement Parameters for Mapping ---
    n_steps_x = 8      # Number of measurement points in the X direction (columns)
    n_steps_y = 44     # Number of measurement points in the Y direction (rows)
    dX = 0.1           # Center-to-center distance in X (mm)
    dY = 0.025         # Center-to-center distance in Y (mm)
    pixel_size_map = (0.1, 0.025) # Define the size of each colored pixel in the heatmap (width, height) in mm
    start_xy = (0.0, 1.0) # Physical starting coordinate (center of the top-left pixel); (startX, startY) in mm
    gap_mm = None # If an additional gap is added between scanned columns, define it here. Usually this is "None"
    map_offset_xy = (-0.15, -start_xy[1]+pixel_size_map[1]/2) # vector for shifting the map data
    trim_edges = True # allows the user to trim the pixels left and down from the translated (0,0)
    color_limit_window = (0.2, 0.8) # Sets the x-range (in mm) used to determine the color scale limits
    colorbar_scale = (-150, 150) # Sets the scale of strain; if default scale is desired: None
    map_name_pfx = f"{sample_name}_stress-map"

    if colorbar_scale and trim_edges:
        output_directory = fl.create_directory(
            f"OutputMaps_UnifiedColorbar-TrimmedEdges/OutputFiles_StressMaps_{sample_name}_{batch_time_suffix}")
    elif colorbar_scale:
        output_directory = fl.create_directory(
            f"OutputMaps_UnifiedColorbar/OutputFiles_StressMaps_{sample_name}_{batch_time_suffix}")
    elif trim_edges:
        output_directory = fl.create_directory(
            f"OutputMaps_TrimmedEdges/OutputFiles_StressMaps_{sample_name}_{batch_time_suffix}")
    else:
        output_directory = fl.create_directory(
            f"OutputMaps_DefaultFormat/OutputFiles_StressMaps_{sample_name}_{batch_time_suffix}")

    # Setup logging
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    logger = logging.getLogger(__name__)

    fl.generate_stress_maps_from_json(
        json_path=json_path,
        youngs_modulus=youngs_modulus,
        poissons_ratio=poissons_ratio,
        n_rows=n_steps_y,
        n_cols=n_steps_x,
        step_size=(dX, dY),
        pixel_size_map=pixel_size_map,
        start_xy=start_xy,
        gap_mm=gap_mm,
        map_offset_xy=map_offset_xy,
        trim_edges=trim_edges,
        color_limit_window=color_limit_window,
        colorbar_scale=colorbar_scale,
        output_dir=output_directory,
        dpi=600,
        map_name_pfx=map_name_pfx,
        logger=logger)

    end_time = time.time()
    logger.info(f"Stress mapping completed in {end_time - start_time:.2f} seconds.")


if __name__ == "__main__":
    map_stress()